# Generated by Django 5.2.1 on 2026-07-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="iin",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="ИИН"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Подтверждён"),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_PERSON", "Клиент (физ. лицо)"),
                    ("CUSTOMER_COMPANY", "Клиент (юр. лицо)"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                (
                    "bin",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="БИН"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Юридический адрес",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
