# Generated by Django 5.2.1 on 2026-07-13 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_client_iin_user_is_verified_alter_client_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_PERSON", "Клиент (физ. лицо)"),
                    ("CUSTOMER_COMPANY", "Клиент (юр. лицо)"),
                    ("SERVICE_BROKER", "Брокер (СВХ)"),
                    ("SERVICE_SVH", "СВХ"),
                    ("SERVICE_LAB", "Лаборатория"),
                    ("SERVICE_LOGISTIC", "Логист"),
                    ("SERVICE_DECLARANT", "Декларант (граница)"),
                    ("BANK", "Банк"),
                    ("PARTNER", "Партнёр-продавец"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=255, verbose_name="Название банка"),
                ),
                (
                    "bik",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="БИК"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Адрес"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="China",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "reg_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Рег. номер компании",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("BROKER", "Брокер (СВХ)"),
                            ("SVH", "СВХ"),
                            ("LAB", "Лаборатория"),
                            ("LOGISTIC", "Логист"),
                            ("DECLARANT", "Декларант (граница)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=255, verbose_name="Название компании / ФИО"
                    ),
                ),
                (
                    "bin",
                    models.CharField(
                        blank=True, default="", max_length=12, verbose_name="БИН"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
