# Generated by Django 5.2.1 on 2026-07-21 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_deal_customer_deal_vehicle_dealassignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Закупка в Китае"),
                            ("LOGISTICS", "Логистика / доставка"),
                            ("CUSTOMS", "Растаможка"),
                            ("CERTIFICATION", "Сертификация (СБКТС/ЭПТС)"),
                            ("SVH", "СВХ / хранение"),
                            ("OTHER", "Прочее"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="core.deal",
                    ),
                ),
            ],
        ),
    ]
