# Generated by Django 5.2.1 on 2026-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_dealactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
