# Generated by Django 5.2.1 on 2026-07-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_user_notifications_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        default="SHAANXI HEAVY DUTY AUTOMOBILE IMPORT AND EXPORT CO., LTD",
                        max_length=255,
                        verbose_name="Продавец",
                    ),
                ),
                (
                    "seller_address",
                    models.TextField(
                        default="CHINA, XIAN CITY, PROVINCE SHAANQI, JINGWEI INDUSTRIAL DISTRICT, SHAANQI AVE, ADMINISTRATIVE CENTER BLDG, 1 APT",
                        verbose_name="Адрес продавца",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        default="CHINA ZHESHANG BANK XI'AN BRANCH",
                        max_length=255,
                        verbose_name="Банк",
                    ),
                ),
                (
                    "bank_address",
                    models.TextField(
                        default="TAIHUA JINMAO INTERNATIONAL. NO. 16. FENGHUI SOUTH ROAD, YANTA DISTRICT, XIAN CITY, SHAANXI PROVINCE",
                        verbose_name="Адрес банка",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        default="7910000011420100067269 (USD)",
                        max_length=120,
                        verbose_name="Счёт (IBAN/ACCOUNT)",
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        default="ZJCBCN2NXXX", max_length=60, verbose_name="SWIFT"
                    ),
                ),
                (
                    "delivery_terms",
                    models.CharField(
                        default="DAP, СВХ НУР ЖОЛЫ, КАЗАХСТАН.",
                        max_length=255,
                        verbose_name="Условия поставки",
                    ),
                ),
                (
                    "timeline",
                    models.TextField(
                        default="Экспортная декларация и регистрация документов в таможенном органе Китая — 1 день.\nПостановка на электронную очередь для выезда из КПП Хоргос (Китай) — 1 день.\nДоставка до СВХ Нур Жолы, Казахстан — 1 день.\nДоставка до лаборатории (установка кнопки СОС, СБКТС и ЭПТС) и СВХ Алматы — 1 день.\nРегистрация и утверждение СБКТС — 2 дня.\nПроверка на соответствие экологическим стандартам ЕАЭС ЕВРО-5 — 3 дня.\nПодача пакета документов в ЦЭД, оплата НДС и пошлины — 2 дня.\nПодача документов в АО «Жасыл Даму» и оплата утильсбора — 1 день.\nУтверждённый ЭПТС — 1 день.\nАвто ЦОН — 1 день.",
                        help_text="По одному пункту на строку",
                        verbose_name="Сроки поставки",
                    ),
                ),
                (
                    "service_center",
                    models.TextField(
                        default="Шахман Центр в Алматы (сервис-центр): ТОО «NOMADCORE», БИН 250440006291. Адрес: Казахстан, Алматинская область, Карасайский район, с.о. Әйтей, село Айтей, КХ АКХ Ленинский, строение 1995, индекс 040900.",
                        verbose_name="Сервис-центр",
                    ),
                ),
                (
                    "show_seal",
                    models.BooleanField(
                        default=True, verbose_name="Показывать печать и подпись"
                    ),
                ),
            ],
            options={
                "verbose_name": "Коммерческое предложение (шаблон)",
                "verbose_name_plural": "Коммерческое предложение (шаблон)",
            },
        ),
    ]
