# Generated by Django 5.2.1 on 2026-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_kpsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="calc_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
