# Generated by Django 5.2.1 on 2026-07-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_deal_calc_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealCalcRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Напр.: Дополнительные расходы, Доставка и граница",
                        max_length=120,
                        verbose_name="Группа",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Строка")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Сумма, ₸",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calc_rows",
                        to="core.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка расчёта",
                "verbose_name_plural": "Строки расчёта",
                "ordering": ["order", "id"],
            },
        ),
    ]
