# Generated by Django 5.2.1 on 2026-07-25 09:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_dealcalcrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalcConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usd_kzt",
                    models.DecimalField(
                        decimal_places=2,
                        default=493.11,
                        max_digits=10,
                        verbose_name="Курс USD→₸ (запасной)",
                    ),
                ),
                (
                    "cny_kzt",
                    models.DecimalField(
                        decimal_places=2,
                        default=68.5,
                        max_digits=10,
                        verbose_name="Курс CNY→₸ (запасной)",
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.16,
                        max_digits=5,
                        verbose_name="НДС (доля, напр. 0.16)",
                    ),
                ),
                (
                    "duty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.1,
                        max_digits=5,
                        verbose_name="Пошлина по умолчанию (доля)",
                    ),
                ),
                (
                    "plate",
                    models.DecimalField(
                        decimal_places=2,
                        default=16963,
                        max_digits=12,
                        verbose_name="Госномер и техпаспорт, ₸",
                    ),
                ),
                (
                    "srtc",
                    models.DecimalField(
                        decimal_places=2,
                        default=17516,
                        max_digits=12,
                        verbose_name="СРТС, ₸",
                    ),
                ),
                (
                    "eptc",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000,
                        max_digits=12,
                        verbose_name="ЭПТС, ₸",
                    ),
                ),
                (
                    "sbkts",
                    models.DecimalField(
                        decimal_places=2,
                        default=150000,
                        max_digits=12,
                        verbose_name="СБКТС, ₸",
                    ),
                ),
                (
                    "sos",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000,
                        max_digits=12,
                        verbose_name="Кнопка SOS, ₸",
                    ),
                ),
                (
                    "customs_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=25950,
                        max_digits=12,
                        verbose_name="Таможенный сбор, ₸",
                    ),
                ),
                (
                    "broker_service",
                    models.DecimalField(
                        decimal_places=2,
                        default=115000,
                        max_digits=12,
                        verbose_name="Услуги брокера на СВХ, ₸",
                    ),
                ),
                (
                    "red_corridor",
                    models.DecimalField(
                        decimal_places=2,
                        default=200000,
                        max_digits=12,
                        verbose_name="Красный коридор, ₸",
                    ),
                ),
                (
                    "adblue",
                    models.DecimalField(
                        decimal_places=2,
                        default=13500,
                        max_digits=12,
                        verbose_name="AdBlue, ₸",
                    ),
                ),
                (
                    "driver",
                    models.DecimalField(
                        decimal_places=2,
                        default=65000,
                        max_digits=12,
                        verbose_name="Водитель, ₸",
                    ),
                ),
                (
                    "insurance",
                    models.DecimalField(
                        decimal_places=2,
                        default=16000,
                        max_digits=12,
                        verbose_name="Страховка, ₸",
                    ),
                ),
                (
                    "toll_road",
                    models.DecimalField(
                        decimal_places=2,
                        default=9000,
                        max_digits=12,
                        verbose_name="Платная дорога, ₸",
                    ),
                ),
                (
                    "svh",
                    models.DecimalField(
                        decimal_places=2,
                        default=91000,
                        max_digits=12,
                        verbose_name="Услуги СВХ, ₸",
                    ),
                ),
                (
                    "advanced",
                    models.JSONField(
                        blank=True,
                        default=core.models._calc_advanced_default,
                        verbose_name="Расширенные (МРП, легковые M1, правила пошлин, дизель)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Калькулятор — настройки",
                "verbose_name_plural": "Калькулятор — настройки",
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="kp_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="E-mail для КП"
            ),
        ),
    ]
