# Generated by Django 5.2.1 on 2026-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_calcconfig_deal_kp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealstage',
            name='done_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealstage',
            name='planned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealstage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
