# Generated by Django 5.2.1 on 2026-07-31 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0013_vehicle_remove_name_and_max_speed_add_category_city_price_kzt"),
        ("core", "0015_dealstage_done_at_dealstage_planned_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("json", "Страница КП"), ("pdf", "PDF с подписью")],
                        default="pdf",
                        max_length=8,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kp_downloads",
                        to="cars.vehicle",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скачивание КП",
                "verbose_name_plural": "Скачивания КП",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_kpdown_created_14a3ea_idx"
                    )
                ],
            },
        ),
    ]
