# Generated by Django 5.2.1 on 2026-08-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0013_vehicle_remove_name_and_max_speed_add_category_city_price_kzt"),
        ("core", "0016_kpdownloadlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpsettings",
            name="kp_valid_days",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Цена в КП зафиксирована по курсу на дату выдачи. По истечении срока документ перевыпускается автоматически.",
                verbose_name="Срок действия КП, дней",
            ),
        ),
        migrations.CreateModel(
            name="KPSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=64, verbose_name="Номер КП")),
                ("issued_on", models.DateField(db_index=True, verbose_name="Выдано")),
                (
                    "valid_until",
                    models.DateField(db_index=True, verbose_name="Действительно до"),
                ),
                (
                    "usd_kzt",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Курс USD→₸"
                    ),
                ),
                (
                    "cny_kzt",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Курс CNY→₸"
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена, USD",
                    ),
                ),
                (
                    "price_cny",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена, CNY",
                    ),
                ),
                (
                    "total_kzt",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Под ключ, ₸"
                    ),
                ),
                (
                    "inputs_fingerprint",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Отпечаток входных данных",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Документ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kp_snapshots",
                        to="cars.vehicle",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "КП — снимок",
                "verbose_name_plural": "КП — снимки",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-created_at"],
                        name="core_kpsnap_vehicle_95eb3b_idx",
                    )
                ],
            },
        ),
    ]
