# Generated by Django 5.2.1 on 2026-02-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorlead',
            name='message',
            field=models.TextField(),
        ),
    ]
