# Generated by Django 5.2.1 on 2026-02-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_calculatorlead_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorlead',
            name='page_url',
            field=models.TextField(blank=True),
        ),
    ]
