# Generated by Django 5.2.1 on 2026-02-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_calculatorlead_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('deal', 'Deal'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
