# Generated by Django 5.2.1 on 2026-02-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calculatorlead_status'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorlead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.product'),
        ),
    ]
