# Generated by Django 5.2.1 on 2026-02-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calculatorlead_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('deal', 'Deal'), ('closed', 'Closed'), ('in_progress', 'В работе'), ('won', 'Продан'), ('lost', 'Потерян')], default='new', max_length=20),
        ),
    ]
