# Generated by Django 5.2.1 on 2026-02-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_calculatorlead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorlead',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
