# Generated by Django 5.2.1 on 2026-02-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_calculatorlead_closed_at_alter_calculatorlead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorlead',
            name='profit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
