# Generated by Django 5.2.1 on 2026-02-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_calculatorlead_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorlead',
            name='profit_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
