# Generated by Django 5.2.1 on 2026-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_calculatorlead_profit_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
    ]
