# Generated by Django 5.2.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_calculatorlead_status'),
        ('cars', '0011_vehicle_engine_power_hp_vehicle_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorlead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='cars.vehicle'),
        ),
    ]
