# Generated by Django 5.2.1 on 2026-07-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_fix_product_fk_column_type"),
        ("core", "0005_deal_customer_deal_vehicle_dealassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorlead",
            name="converted_deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_leads",
                to="core.deal",
            ),
        ),
    ]
