# Generated by Django 5.2 on 2025-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, default='', max_length=120)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage_km', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
