# Generated by Django 5.2.1 on 2026-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_vehicle_body_type_alter_vehicle_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
