# Generated by Django 5.2.1 on 2026-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_vehicle_body_type_alter_vehicle_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='weight_t',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Полная масса ТС в тоннах', max_digits=5, null=True),
        ),
    ]
