# Generated by Django 5.2.1 on 2026-07-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_vehicle_weight_t"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="price_cny",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
