# Generated by Django 5.2.1 on 2026-07-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_vehicle_price_cny"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Доп. фото галереи — список ссылок, например: ["https://.../1.jpg", "https://.../2.jpg"]',
            ),
        ),
    ]
