# Generated by Django 5.2.1 on 2026-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_vehicle_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="availability",
            field=models.CharField(
                choices=[
                    ("in_stock", "В наличии"),
                    ("out_of_stock", "Нет в наличии"),
                    ("on_order", "На заказ"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
    ]
