# Generated by Django 5.2.1 on 2026-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_vehicle_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="extra_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Любые дополнительные детали о технике — выводится на странице товара",
                verbose_name="Доп. информация",
            ),
        ),
    ]
