# Generated by Django 5.2.1 on 2026-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_vehicle_extra_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="tiktok_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Ссылка на видео TikTok — покажется последним слайдом в галерее фото",
                verbose_name="Видео-обзор TikTok",
            ),
        ),
    ]
