# Generated by Django 5.2.1 on 2026-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_vehicle_tiktok_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="engine_power_hp",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Мощность двигателя, л.с."
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="gearbox",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: механика, автомат",
                max_length=60,
                verbose_name="КПП",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="load_capacity_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Грузоподъёмность, т",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="max_speed_kmh",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Макс. скорость, км/ч"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="wheel_formula",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: 6x4",
                max_length=20,
                verbose_name="Колёсная формула",
            ),
        ),
    ]
