# Generated by Django 5.2.1 on 2026-07-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_vehicle_engine_power_hp_vehicle_gearbox_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_approved",
            field=models.BooleanField(
                default=True,
                help_text="Объявления клиентов скрыты из публичного каталога, пока админ не одобрит",
                verbose_name="Одобрено",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — официальный каталог; заполнено — объявление клиента",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle_listings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления",
            ),
        ),
    ]
