# Generated by Django 5.2.1 on 2026-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0012_vehicle_is_approved_vehicle_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="max_speed_kmh",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="name",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Тип техники, например: Самосвал, Тягач, Кран",
                max_length=120,
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price_kzt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Цена, ₸",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отображается как заголовок в каталоге и на странице техники",
                max_length=120,
                verbose_name="Название / модель",
            ),
        ),
    ]
