# Generated by Django 5.2 on 2025-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ')], default='Под заказ', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('specs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
