# Generated by Django 5.2.1 on 2026-02-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
